# Generated by Django 2.1.2 on 2018-11-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=100, unique=True)),
                ('opis', models.CharField(max_length=500)),
                ('ilosc_miejsc', models.SmallIntegerField()),
                ('cena', models.IntegerField()),
                ('internet', models.BooleanField()),
                ('telewizor', models.BooleanField()),
                ('basen', models.BooleanField()),
                ('sauna', models.BooleanField()),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
