# Generated by Django 2.1.2 on 2018-11-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartament',
            old_name='cena',
            new_name='cena_za_dobe',
        ),
    ]
