# Generated by Django 2.1.3 on 2018-12-02 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_auto_20181118_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezerwacja_od', models.DateField(db_index=True, null=True)),
                ('rezerwacja_do', models.DateField(db_index=True, null=True)),
                ('status', models.CharField(choices=[('niezatwierdzony', 'Niezatwierdzony'), ('zatwierdzony', 'Zatwierdzony'), ('odrzucony', 'Odrzucony')], default='niezatwierdzony', max_length=255)),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Apartament')),
                ('kto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
