# Generated by Django 2.1.3 on 2018-12-15 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_rezerwacja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc_kom', models.TextField()),
                ('dodano_dnia', models.DateField()),
                ('odpowiedz', models.TextField(null=True)),
                ('odpowiedz_data', models.DateField(null=True)),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Apartament')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
